### ISSUE TITLE
Implement basic plug-in (1 motor only)

### ISSUE THREAD

**Issue by jpromerob** [omkarbhoite25/KTH-Neuro-Computing-Systems#3]
Once Issue #2  is done, you might be able to start creating your own stuff (plugin-wise).

1. Install [Gazebo](http://gazebosim.org/tutorials?tut=install_ubuntu) (use version **11.x.x)**
2. Install [ROS](http://wiki.ros.org/melodic/Installation/Ubuntu) + [catkin](http://wiki.ros.org/catkin) (use **noetic** version)
3. Follow the tutorial presented here: [Video #1](https://www.youtube.com/watch?v=LRjT_1huVKY), [Video #2](https://www.youtube.com/watch?v=kLJt5U7wrGQ), [Repository](https://bitbucket.org/theconstructcore/tc_gazebo_custom_plugins/src/master/)
4. Based on the acquired knowledge, create a plugin that allows you to control the Dynamixel MX-28 by position, velocity, torque, etc)

**Comment by omkarbhoite25** [comment]
Done
